# Generated by Django 2.1 on 2019-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='危険箇所の場所')),
                ('content', models.TextField(max_length=100, verbose_name='危険箇所である理由')),
                ('author', models.CharField(max_length=50, verbose_name='投稿者')),
                ('images', models.ImageField(upload_to='', verbose_name='画像')),
                ('dangerous', models.IntegerField(blank=True, default=0, null=True, verbose_name='危険度')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='投稿日')),
            ],
            options={
                'verbose_name': '豊川市内危険箇所一覧',
                'verbose_name_plural': '豊川市内危険箇所一覧',
                'ordering': ['-dangerous'],
            },
        ),
    ]
